stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "myapp:${CI_COMMIT_SHA}"

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet publish "WebApplication.csproj" -c Release -o out

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker-compose build
    - docker-compose  up -d
