stages:
  - build
  - deploy

variables:
  DOCKER_HOST: "tcp://docker:2375"


build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet publish "WebApplication.csproj" -c Release -o out

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
    - command: ["--host=fd://"]
  variables:
      DOCKER_DRIVER: overlay2
      DOCKER_HOST: tcp://docker:2375
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKERHUB_TOKEN"
    - docker-compose build
    - docker-compose  up -d
