image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - deploy

before_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

build:
  stage: build
  script:
    - docker build -t $DOCKER_USERNAME/barak:latest .
  
deploy:
  stage: deploy
  script:
    - docker push $DOCKER_USERNAME/barak:latest